import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { NextRequest, NextResponse } from "next/server";
import {
   searchTracksByMood,
   createPlaylist,
   addTracksToPlaylist,
   Mood,
} from "@/lib/spotify";

export async function POST(req: NextRequest) {
   try {
      const session = await getServerSession(authOptions);

      if (!session?.accessToken) {
         return NextResponse.json(
            { error: "Not authenticated" },
            { status: 401 }
         );
      }

      const body = await req.json();
      const mood = body.mood as Mood;

      if (!mood) {
         return NextResponse.json(
            { error: "Mood is required" },
            { status: 400 }
         );
      }

      const accessToken = session.accessToken as string;

      // Step 1: Search for tracks matching this mood
      const tracks = await searchTracksByMood(mood, accessToken, 20);

      if (!tracks || tracks.length === 0) {
         return NextResponse.json(
            { error: "No tracks found for this mood. Try a different one!" },
            { status: 404 }
         );
      }

      // Step 2: Try to create a playlist
      const moodLabel = mood.charAt(0).toUpperCase() + mood.slice(1);
      const now = new Date();
      const dateStr = now.toLocaleDateString("en-US", {
         month: "short",
         day: "numeric",
         year: "numeric",
      });
      const playlistName = `${moodLabel} Vibes — ${dateStr}`;
      const playlistDescription = `Generated by Moodify · ${moodLabel} mood playlist · ${tracks.length} tracks`;

      let playlistResult = null;

      try {
         const playlist = await createPlaylist(
            playlistName,
            playlistDescription,
            accessToken
         );

         // Step 3: Add tracks to the playlist
         const trackUris = tracks.map((t) => t.uri);
         await addTracksToPlaylist(playlist.id, trackUris, accessToken);

         playlistResult = {
            name: playlistName,
            url: playlist.external_urls.spotify,
            trackCount: tracks.length,
         };
      } catch (playlistError) {
         // Playlist creation failed (403 in dev mode), still return tracks
         console.warn(
            "Could not create playlist (likely dev-mode restriction):",
            playlistError
         );
      }

      return NextResponse.json({
         success: true,
         playlist: playlistResult,
         tracks: tracks.map((t) => ({
            name: t.name,
            artists: t.artists.map((a) => a.name).join(", "),
            album: t.album.name,
            albumArt: t.album.images[0]?.url,
            duration: t.duration_ms,
            url: t.external_urls.spotify,
         })),
      });
   } catch (error: unknown) {
      console.error("Playlist generation error:", error);
      const message =
         error instanceof Error ? error.message : "Something went wrong";
      return NextResponse.json({ error: message }, { status: 500 });
   }
}
